DELETE FROM VGER_SUPPORT.CLICC_COUNTS;
COMMIT;
INSERT INTO VGER_SUPPORT.CLICC_COUNTS(LOC,CHROMEBOOKS_IN,MAC_LAPTOPS_IN,WIN_LAPTOPS_IN,IPADS_IN) VALUES ('Powell',5,10,15,20);
INSERT INTO VGER_SUPPORT.CLICC_COUNTS(LOC,CHROMEBOOKS_IN,MAC_LAPTOPS_IN,WIN_LAPTOPS_IN,IPADS_IN) VALUES ('YRL',10,0,5,2);
COMMIT;