name: Maven PR Build

# We require all commits go through PR on GitHub
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Maven PR Builder (JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    env:
      MAVEN_CACHE_KEY: ${{ secrets.MAVEN_CACHE_KEY }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      UCLALIBRARY_SNYK_ORG: ${{ secrets.UCLALIBRARY_SNYK_ORG }}
    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - name: Check out code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@8764a52df183aa0ccea74521dfd9d506ffc7a19a # v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Set up Maven cache
        uses: actions/cache@0781355a23dac32fd3bac414512f4b903437991a # v2
        if: ${{ env.MAVEN_CACHE_KEY }}
        with:
          path: ~/.m2
          key: uclalibrary-cache-${{ secrets.MAVEN_CACHE_KEY }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: uclalibrary-cache-${{ secrets.MAVEN_CACHE_KEY }}-
      - name: Build with Maven, with optional environment variables set
        uses: samuelmeuli/action-maven-publish@201a45a3f311b2ee888f252ba9f4194257545709 # v1.4.0
        with:
          maven_goals_phases: "clean verify"
          maven_profiles: default
          maven_args: >
            -V -ntp -Dorg.slf4j.simpleLogger.log.net.sourceforge.pmd=error -Ddocker.showLogs=true
            -Dsnyk.skip=${{ secrets.SKIP_SNYK }}
